language: php
sudo: true

php:
  - 5.5

#addons:
#  apt:
#    packages:
#      - php5-cgi
#      - php5-mysql
#      - php5-curl

mysql:
  database: drupal
  username: root

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*@dev

before_script:

  # Create the database.
  - "mysql -e 'create database drupal;'"
  - phpenv rehash

  # Build the distrobution.
  - pwd
  - bash scripts/setup
  - bash scripts/build.sh
  - cd /home/travis/build/Midburn/burning/www

  # Install and migrate.
  - drush si -y burning --account-name=admin --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal
  - drush mi --all --user=1

  # Minor setup.
  - drush vset burning_push_notifications TRUE

  # Fire up the server
  - php -S 127.0.0.1:8888 > ~/rs.log 2>&1 &

  # Behat setup.
  - cd profiles/burning/behat
  - cp behat.local.yml.travis behat.local.yml
  - composer install
  - bin/behat --init

script:
  # Run behat.
  - bin/behat --tags=~wip

#after_script:
#  - cat ~/grunt.log
  - cat ~/rs.log
